---
title: "avito"
author: "Zak Kann"
date: "July 6, 2015"
output: pdf_document
---

Load libraries:
``` {r libraries, message=FALSE}
library(data.table)
library(RSQLite)
library(caret)
```

```{r logloss, echo=FALSE}
logloss <- function (data, lev = NULL, model = NULL) {
    LogLos <- function(actual, pred, eps = 1e-15) {
        stopifnot(all(dim(actual) == dim(pred)))
        pred[pred < eps] <- eps
        pred[pred > 1 - eps] <- 1 - eps
        -sum(actual * log(pred)) / nrow(pred)
    }
    if (is.character(data$obs)) data$obs <- factor(data$obs, levels = lev)
    pred <- data[, "pred"]
    obs <- data[, "obs"]
    isNA <- is.na(pred)
    pred <- pred[!isNA]
    obs <- obs[!isNA]
    data <- data[!isNA, ]
    cls <- levels(obs)

    if (length(obs) + length(pred) == 0) {
        out <- rep(NA, 2)
    } else {
        pred <- factor(pred, levels = levels(obs))
        require("e1071")
        out <- unlist(e1071::classAgreement(table(obs, pred)))[c("diag", "kappa")]
        probs <- data[, cls]
        actual <- model.matrix(~ obs - 1)
        out2 <- LogLos(actual = actual, pred = probs)
    }
    out <- c(out, out2)
    names(out) <- c("Accuracy", "Kappa", "LogLoss")

    if (any(is.nan(out))) out[is.nan(out)] <- NA
    out
}
rfFuncs$summary = logloss
```

Connect to database and examine tables:
```{r open.db}
db <- dbConnect(SQLite(), dbname="input/database.sqlite")
tables <- dbListTables(db)
for (table in tables) {
  cat(table, ":\n", sep="")
  print(dbListFields(db,table))
  cat("\n")
}

```

Remove unnecessary rows:
```{r trim}
dbSendQuery(db, "DELETE FROM trainSearchStream WHERE ObjectType<>3")
dbSendQuery(db, "DELETE FROM testSearchStream WHERE ObjectType<>3")
dbSendQuery(db, "DELETE FROM AdsInfo WHERE IsContext=0")
```