args <- commandArgs(trailingOnly = TRUE)
res1 <- read.csv(args[1], header = TRUE, sep=",")
res2 <- read.csv(args[2], header = TRUE, sep=",")
#res3 <- read.csv(args[3], header = TRUE, sep=",")
#res4 <- read.csv(args[4], header = TRUE, sep=",")
#res5 <- read.csv(args[5], header = TRUE, sep=",")
#res6 <- read.csv(args[5], header = TRUE, sep=",")
#res7 <- read.csv(args[5], header = TRUE, sep=",")
#res8 <- read.csv(args[5], header = TRUE, sep=",")
comb <- data.frame(a=res1$Prediction, b=res2$Prediction)#, c=res3$prob, d=res4$prob, e=res5$prob, f=res6$prob, g=res7$prob)#, h=res8$prob)
res1$Prediction = rowMeans(comb)
write.csv(res1, file="combined.csv", row.names=FALSE, quote=FALSE)
